$(document).ready(function() {
	var a = [{
		label: "AngularJS",
		url: "#",
		target: "_top"
	}, {
		label: "Bootstrap",
		url: "#",
		target: "_top"
	}, {
		label: "Ajax",
		url: "#",
		target: "_top"
	}, {
		label: "AeffterEffects",
		url: "#",
		target: "_top"
	}, {
		label: "PhotoShop",
		url: "#",
		target: "_top"
	}, {
		label: "JavaScript",
		url: "#",
		target: "_top"
	}, {
		label: "HTML5",
		url: "#",
		target: "_top"
	}, {
		label: "CSS3",
		url: "#",
		target: "_top"
	}, {
		label: "Jquery",
		url: "#",
		target: "_top"
	}, {
		label: "WebApp",
		url: "#",
		target: "_top"
	}, {
		label: "MySQL",
		url: "#",
		target: "_top"
	}, {
		label: "PHP",
		url: "http://down.admin5.com/",
		target: "_top"
	}, {
		label: "Premiere",
		url: "#",
		target: "_top"
	}, {
		label: "JAVA",
		url: "#",
		target: "_top"
	}, {
		label: "Node.js",
		url: "#",
		target: "_top"
	}, {
		label: "Hbulider",
		url: "#",
		target: "_top"
	}, {
		label: "WebStorm",
		url: "#",
		target: "_top"
	}, {
		label: "Sublim",
		url: "#",
		target: "_top"
	}, {
		label: "Svn",
		url: "#",
		target: "_top"
	}, {
		label: "XAMPP",
		url: "#",
		target: "_top"
	}, {
		label: "DreamWeaver",
		url: "#",
		target: "_top"
	}, {
		label: "Avolon",
		url: "#",
		target: "_top"
	}, {
		label: "Move.js",
		url: "#",
		target: "_top"
	}, {
		label: "Velocity.js",
		url: "#",
		target: "_top"
	}, {
		label: "Fullpage.js",
		url: "#",
		target: "_top"
	}, ];
	var b = {
		entries: a,
		width: 640,
		height: 510,
		radius: "65%",
		radiusMin: 75,
		bgDraw: true,
		bgColor: "transparent",
		opacityOver: 1,
		opacityOut: 0.05,
		opacitySpeed: 6,
		fov: 800,
		speed: 0.5,
		fontFamily: "Oswald, Arial, sans-serif",
		fontSize: "15",
		fontColor: "#fff",
		fontWeight: "normal",
		fontStyle: "normal",
		fontStretch: "normal",
		fontToUpperCase: true
	};
	$("#tag-cloud").svg3DTagCloud(b)
});